os:
    - linux
    - osx
language: generic
env:
    - PYTHON_VERSION="3.3"
    - PYTHON_VERSION="3.4"
    - PYTHON_VERSION="3.5"
matrix:
  allow_failures:
    - os: osx

addons:
  apt:
    packages:
    - libgsl0-dev
    - gsl-bin
before_install:
  - >
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - pwd
  - >
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export PATH=/home/travis/miniconda3/bin:$PATH
    else
      export PATH=/Users/travis/miniconda3/bin:$PATH
    fi
  - conda update --yes conda
install:
  - conda install --yes python=$PYTHON_VERSION gcc atlas numpy scipy cython
  # - conda install --yes -c https://conda.anaconda.org/asmeurer gsl
  - gcc --version
  - python --version
  - pip install nose2 nose-cov
  - pip install coveralls
  - make
  # - conda install --yes -c dan_blanchard python-coveralls nose-cov
script:
    - make test-coverage
after_success:
  - coveralls
