language: python
python:
    # - "3.3"
    # - "3.4"
    - "3.5_with_system_site_packages"
addons:
  apt:
    packages:
    - python3-numpy
    - python3-scipy
before_install:
    - pip install nose2
script:
    - nose2
