language: python
python:
    # - "3.3"
    # - "3.4"
    - "3.5"
# addons:
#   apt:
#     packages:
#     # - python3-numpy
#     # - python3-scipy
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda update --yes conda
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION gcc atlas numpy scipy cython
  - conda install -yes -c https://conda.anaconda.org/asmeurer gsl
  - gcc --version
  - python --version
  - pip install nose2
  - make
  # - conda install --yes -c dan_blanchard python-coveralls nose-cov
script:
    - nose2
