language: python
python:
    - "3.3"
    - "3.4"
    - "3.5"
addons:
  apt:
    packages:
    - libgsl0-dev
    - gsl-bin
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda update --yes conda
  # Fix multiprocess
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION gcc atlas numpy scipy cython
  # - conda install --yes -c https://conda.anaconda.org/asmeurer gsl
  - gcc --version
  - python --version
  - pip install nose2 nose-cov
  - pip install coveralls
  - make
  # - conda install --yes -c dan_blanchard python-coveralls nose-cov
script:
    - make test-coverage
after_success:
  - coveralls
